### ISSUE TITLE
Spikes destroy items?

### ISSUE THREAD

**Issue by sweetsosweet** [Lemonszz/trap-expansion#2]
Please fill out this template when submitting an issue.

---
**Mod Version**:  
1.0.0

**Forge Version**:
14.23.4.2759

**This issue occurs on the lastest version of Forge? (Y/N)**:
Y

**What happens**:
It seems the spikes destroy items as well as kill mobs. Is that intended? Seems like it would make them kind of useless for mob farming.

**Comment by Lemonszz** [comment]
Yes this is intended. There are ways of them not destroying drops, you just have to get a little bit creative. (Try putting them on the ceiling).
