### ISSUE TITLE
Spikes don't kill bats

### ISSUE THREAD

**Issue by calloatti** [Lemonszz/trap-expansion#7]
Please fill out this template when submitting an issue.

---
**Mod Version**:  
trapexpansion-FABRIC-1.14.1-1.1.0

**MC Version**:
MC 1.14.3

**What happens**:
https://youtu.be/9q5dQjtRozI

**Comment by Lemonszz** [comment]
It looks like its's not in the spike block, it's in the pane. Replacing the pane with a full block would probably solve your issue.
