### ISSUE TITLE
[1.14.4] Activated Spike Blocks cause server-side crash

### ISSUE THREAD

**Issue by erindal** [Lemonszz/trap-expansion#9]
Please fill out this template when submitting an issue.

---
**Mod Version**:  
Trap Expansion 1.1.0
**~~Forge~~ Fabric Version**:
Fabric Loader 0.6.1+build.165

**This issue occurs on the lastest version of Forge? (Y/N)**:
N/A

**Crash Log (Post to Pastebin/Other Text hosting)**: 
https://paste.ee/p/7KzRV

**What happens**:
Activated a spike trap, caused game to crash, loading world crashes.

**Comment by Lemonszz** [comment]
Thanks for the report, but issues for the fabric version should be reported on the fabric repo, as another developer is maintaining that version.

https://github.com/Lemonszz/trap-expansion-fabric

**Comment by erindal** [comment]
@Lemonszz Could you update the curseforge description to indicate there is a separate project for the Fabric version? I'm sure I'm not alone in that I was not aware of it. Also maybe label the old Fabric version as out of date.
